### ISSUE TITLE
how to enforce quotes?

### ISSUE THREAD

**Issue by timoschilling** [Locale/localeapp#164]
Is there a way to enforce that all pulled values have the same quote?

Here is a example from the activeadmin/activeadmin de.yml (pulled form localeapp):
```yaml
de:
  active_admin:
    batch_actions:
      action_label: "%{title} ausgewählte"
      button_label: Stapelverarbeitung
      delete_confirmation: Sind Sie sicher dass sie diese %{plural_model} löschen wollen?
      selection_toggle_explanation: "(Auswahl umschalten)"
```
