### ISSUE TITLE
Mishandling of YAML lists

### ISSUE THREAD

**Issue by frane** [Locale/localeapp#5]
Localeapp seems to have some problems with YAML lists.

In my case the following date translation construct (in German) doesn't appear in the web app:

```
de:  
  date: 
    abbr_day_names: 
      - So
      - Mo
      - Di
      - Mi
      - Do
      - Fr
      - Sa
    abbr_month_names: 
      - ~
      - Jan
      - Feb
      - Mär
      - Apr
      - Mai
      - Jun
      - Jul
      - Aug
      - Sep
      - Okt
      - Nov
      - Dez
    day_names: 
      - Sonntag
      - Montag
      - Dienstag
      - Mittwoch
      - Donnerstag
      - Freitag
      - Samstag
    formats: 
      default: "%d.%m.%Y"
      long: "%e. %B %Y"
      only_day: "%e"
      short: "%e. %b"
    month_names: 
      - ~
      - Januar
      - Februar
      - März
      - April
      - Mai
      - Juni
      - Juli
      - August
      - September
      - Oktober
      - November
      - Dezember
    order: 
      - :day
      - :month
      - :year
```

The only thing I see in the web app is `TRANSLATIONS -> date -> order` with order having the value `["day", "month", "year"]`.
When I do a `localeapp pull`, the pulled locale file contains the above listed construct. The only exception is that the list items in `order` are strings and not symbols, as they need to be to work properly with the datetime_select form helper.

``` ...
    order:
      - day
      - month
      - year
```
