### ISSUE TITLE
Bad export of string keys

### ISSUE THREAD

**Issue by jhmegorei** [Locale/localeapp#84]
When using string keys, the import works fine, but the export does not work (see example below)

Input

``` yaml
de:
  fixed:
    "yes": "Ja"
    "no": "Nein"
```

Output

``` yaml
de:
  fixed:
    ? "no"
    : Nein
    ? "yes"
    : Ja
```

Is there any way (besides changing the key names) to make string keys work like expected when exporting?
